FROM ubuntu:22.04

# Avoids prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    gawk wget git diffstat unzip texinfo gcc build-essential \
    chrpath socat cpio python3 python3-pip python3-pexpect xz-utils \
    debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa \
    libsdl1.2-dev pylint xterm rsync sudo locales qemu-system-x86 \
    vim curl nano less locales && \
    locale-gen en_US.UTF-8

RUN apt-get update && apt-get install -y \
  file lz4 zstd


ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Create a user (optional but recommended)
RUN useradd -ms /bin/bash yocto && echo "yocto ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER yocto
WORKDIR /home/yocto

# Clone poky (Yocto project reference distro)
RUN git clone -b kirkstone git://git.yoctoproject.org/poky.git

# Set up environment variables
ENV TEMPLATECONF=/home/yocto/poky/meta-poky/conf
ENV PATH=/home/yocto/poky/scripts:$PATH

COPY ./meta-dspcoder /home/yocto/poky/meta-dspcoder

# RUN /bin/bash -c "cd /home/yocto/poky && \
#     source oe-init-build-env && \
#     bitbake-layers add-layer ../meta-dspcoder && \
#     bitbake dspcoder"
